name:                mazer-hs
version:             0.0.0.1
github:              "OliverMead/mazer-hs"
license:             BSD3
author:              "Oliver Mead"
maintainer:          "oliver.j.mead@protonmail.com"
copyright:           "Oliver Mead 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/OliverMead/mazer-hs#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- utility-ht

library:
  source-dirs: src

executables:
  mazer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mazer-hs

tests:
  mazer-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mazer-hs
